wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpapers/
    fit_mode = cover    # contain | cover | tile | fill
    timeout = 600        # Sec
    order = random
    recursive = true
}
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpapers/
    fit_mode = cover
    timeout = 600
    order = random
    recursive = true
}
# Spalsh
splash = false
splash_offset = 20
splash_opacity = 0.8
