# qings environment config
EDITOR=nvim             # 编辑器
LC_ALL=zh_CN.UTF-8      # 语言
XMODIFIERS=@im=fcitx    # 输入法
                        # proxy
proxy_host=127.0.0.1:20122
http_proxy=http://${proxy_host}
https_proxy=http://${proxy_host}
all_proxy=socks5://${proxy_host}
no_proxy=localhost,127.0.0.1,::1
