# qings environment config
# 编辑器
EDITOR=nvim
# 语言
LANG=zh_CN.UTF-8
LC_ALL=zh_CN.UTF-8
# 输入法
XMODIFIERS=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
# 深色主题
GTK_THEME=Adwaita:dark
QT_QPA_PLATFORMTHEME=gtk3
# 缩放
GDK_SCALE=2
QT_SCALE_FACTOR=1.6
XCURSOR_SIZE=24
HYPRCURSOR_SIZE=24
# 代理
# proxy_host=192.168.6.5:20122
proxy_host=127.0.0.1:20122
http_proxy=http://${proxy_host}
https_proxy=http://${proxy_host}
all_proxy=socks5://${proxy_host}
no_proxy=localhost,127.0.0.1,::1
