# qings environment config
EDITOR=nvim             # 编辑器
LC_ALL=zh_CN.UTF-8      # 语言
# 输入法
XMODIFIERS=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
# proxy
proxy_host=127.0.0.1:20122
http_proxy=http://${proxy_host}
https_proxy=http://${proxy_host}
all_proxy=socks5://${proxy_host}
no_proxy=localhost,127.0.0.1,::1
